# Generated by Django 3.0.3 on 2020-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
                ('secure_string', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
